const validTransitions = {
  INTENT_RECEIVED: ['INTENT_PARSED', 'AMBIGUOUS_REQUEST'],
  INTENT_PARSED: ['RETRIEVING'],
  AMBIGUOUS_REQUEST: ['INTENT_RECEIVED'],
  RETRIEVING: ['CANDIDATES_FOUND', 'NO_PRODUCT_FOUND'],
  NO_PRODUCT_FOUND: ['INTENT_RECEIVED'],
  CANDIDATES_FOUND: ['FILTERED'],
  FILTERED: ['RERANKED'],
  RERANKED: ['PRODUCT_SELECTED'],
  PRODUCT_SELECTED: ['AWAITING_MANDATE'],
  AWAITING_MANDATE: ['MANDATE_ACTIVE', 'USER_REJECTED'],
  USER_REJECTED: ['PRODUCT_SELECTED'],
  MANDATE_ACTIVE: ['REVALIDATING'],
  REVALIDATING: ['ORDER_CREATED', 'OUT_OF_STOCK', 'PRICE_CHANGED', 'DELIVERY_CHANGED', 'POLICY_BLOCKED', 'AUTHORIZATION_EXCEEDED'],
  OUT_OF_STOCK: ['RETRIEVING'],
  PRICE_CHANGED: ['AWAITING_MANDATE'],
  DELIVERY_CHANGED: ['AWAITING_MANDATE'],
  POLICY_BLOCKED: ['AWAITING_MANDATE', 'PRODUCT_SELECTED'],
  AUTHORIZATION_EXCEEDED: ['AWAITING_MANDATE'],
  ORDER_CREATED: ['PAYMENT_PENDING', 'ORDER_FAILED'],
  ORDER_FAILED: ['REVALIDATING'],
  PAYMENT_PENDING: ['PAYMENT_VERIFICATION', 'PAYMENT_FAILED', 'PAYMENT_TIMEOUT'],
  PAYMENT_FAILED: ['PAYMENT_PENDING', 'AWAITING_MANDATE'],
  PAYMENT_TIMEOUT: ['PAYMENT_PENDING'],
  PAYMENT_VERIFICATION: ['PAID', 'VERIFICATION_FAILED'],
  VERIFICATION_FAILED: ['PAYMENT_VERIFICATION'],
  PAID: ['COMPLETED']
};

function transitionState(currentState, nextState) {
  if (!validTransitions[currentState]) {
    throw new Error(`Invalid current state: ${currentState}`);
  }
  if (!validTransitions[currentState].includes(nextState)) {
    throw new Error(`Invalid transition from ${currentState} to ${nextState}`);
  }
  return nextState;
}

module.exports = { transitionState, validTransitions };
